name: Supercar Scraper

on:
  schedule:
    - cron: "0 6 * * *"  # daily at 6am UTC
  workflow_dispatch:      # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: main  # change if your default branch is master

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      # Step 4: Run scraper
      - name: Run scraper
        run: python scraper.py

      # Step 5: Debug - list files
      - name: List files
        run: ls -la

      # Step 6: Upload CSV as artifact
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: supercars-data
          path: supercars.csv
